### all heroes
GET http://localhost:3000/api/heroes
Content-Type: application/json

### hero by id
GET http://localhost:3000/api/heroes/704
Content-Type: application/json

### new hero
POST http://localhost:3000/api/heroes
Content-Type: application/json

{
  "name": "Hero XXX",
  "description": "Wrong descrption"
}

### delete hero by id
DELETE http://localhost:3000/api/heroes/623


### update hero
PUT http://localhost:3000/api/heroes/704
Content-Type: application/json

{
  "name": "Spider Man",
  "description": "The amazing guy"
}
