### all heroes
GET http://localhost:3000/api/heroes
Content-Type: application/json

### hero by id
GET http://localhost:3000/api/heroes/1
Content-Type: application/json

### new hero
POST http://localhost:3000/api/heroes
Content-Type: application/json

{
  "name": "Hero 1",
  "description": "A great hero to test"
}

### delete hero by id
DELETE http://localhost:3000/api/heroes/623
