echo "CREATE TABLE heroes (
    hero_id NUMBER(11) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1),
    name VARCHAR2(100) NOT NULL,
    description VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_heroes PRIMARY KEY (hero_id)
);

INSERT INTO heroes (name, description) VALUES ('Superman', 'The Man of Steel');
INSERT INTO heroes (name, description) VALUES ('Batman', 'The Dark Knight');
INSERT INTO heroes (name, description) VALUES ('Wonder Woman', 'The Amazonian Princess');
INSERT INTO heroes (name, description) VALUES ('The Flash', 'The Scarlet Speedster');
INSERT INTO heroes (name, description) VALUES ('Aquaman', 'The King of Atlantis');
INSERT INTO heroes (name, description) VALUES ('Green Lantern', 'The Emerald Knight');
INSERT INTO heroes (name, description) VALUES ('Cyborg', 'Half Man, Half Machine');
INSERT INTO heroes (name, description) VALUES ('Shazam', 'The Worlds Mightiest Mortal');
INSERT INTO heroes (name, description) VALUES ('Green Arrow', 'The Emerald Archer');
INSERT INTO heroes (name, description) VALUES ('Batwoman', 'The Dark Knight Detective');

COMMIT;" | sqlplus -s test/test@//localhost/XEPDB1
